# Generated by Django 4.2.3 on 2023-07-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_activity_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
