# Generated by Django 4.2.3 on 2023-07-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='name',
            field=models.CharField(default='emptyexit', max_length=64),
        ),
    ]
