# Generated by Django 4.2.3 on 2023-07-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tariff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(default='empty', max_length=64),
        ),
    ]
