# Generated by Django 4.2.3 on 2023-07-31 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_cookingsteps_remove_recipe_how_to_cook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingsteps',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe'),
            preserve_default=False,
        ),
    ]
