# Generated by Django 4.2.3 on 2023-07-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodinreport',
            old_name='Report',
            new_name='report',
        ),
    ]
