# Generated by Django 4.2.3 on 2023-07-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_rename_report_foodinreport_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
