# Generated by Django 4.2.3 on 2023-07-10 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_dailyreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='report_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='diary.reporttype'),
            preserve_default=False,
        ),
    ]
