# Generated by Django 4.2.3 on 2023-07-10 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_foodinreport_calories_foodinreport_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinreport',
            name='calories',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='foodinreport',
            name='carbohydrates',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='foodinreport',
            name='protein',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='foodinreport',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
