# Generated by Django 4.2.3 on 2023-07-10 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_alter_foodinreport_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinreport',
            name='fat',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
