# Generated by Django 4.2.3 on 2023-07-17 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0008_alter_foodinreport_fat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodinreport',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='foodinreport',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='foodinreport',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='foodinreport',
            name='protein',
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('date', 'user')},
        ),
    ]
