# Generated by Django 4.2.3 on 2023-07-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_remove_foodinreport_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(),
        ),
    ]
