# Generated by Django 4.2.3 on 2023-07-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_alter_dailyreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinreport',
            name='report_type',
            field=models.SmallIntegerField(choices=[(0, 'Завтрак'), (1, 'Обед'), (2, 'Ужин')]),
        ),
        migrations.DeleteModel(
            name='ReportType',
        ),
    ]
